### ISSUE TITLE
Proposta de melhorias no repositório

### ISSUE THREAD

**Issue by guaracy** [maniero/SOpt#15]
Primeiro, parabéns pelo trabalho. 

Abaixo alguns detalhes que **eu** considerei que poderiam ser melhorados. Posso fazer um programinha para automatizar a tarefa. Não continuei pois não sei se a proposta seria interessante/aceita.

1. Poderia colocar um link no README.md para o arquivo Conceptual.md que possui muita informação relevante.

2. Achei que o arquivo Conceptual.md fica com pouca visibilidade, pricipalmente no diretório da linguagem (início, meio, fim). Trocando para README.md eles seriam mostrados automaticamente, facilitando para quem acessar o SOpt. (tarefa automatizada)

3. Considerando a implementação do item dois, seria interessante relacionar os programas e a funcionalidade de cada um. Poderia ficar algo como (tarefa automatizada):

#### Conteúdo existente no Conceptual.md
----
#### Programas

java - Montando updates em tempo de execução : [QueryBuilder.pas](QueryBuilder.pas)
matemática - Como usar expoente em Pascal? : [Power.pas](Power.pas)
delphi - Por que Shortstring consome mais memória do que uma String comum? : [String.pas](String.pas)
delphi - Descobrir se item está em array : [StringInArray.pas](StringInArray.pas)

**Comment by maniero** [comment]
Gostei e vou adotar sim.

Eu não sei se entendi bem o item 3, pode desenvolver mais? Não sei se precisa de algo para automatizar, mas estou aberto para escutar sobre isso. Pode ser que não esteja claro o que são as postagens conceituais.

Sempre que eu tenho código na minha resposta, eu coloco aqui e tem um link para a resposta. Quando não tem código eu coloco no `conceptual.md`, assim passa ter link para resposta e daqui a pessoa pode achar conteúdo relevante. Nem tudo eu trago pra cá, precisa ter tido certa visibilidade e o assunto ser interessante. Se tiver código vem tudo.

Eu não sabia que este repositório teria o sucesso que teve :D Fiz pra me ajudar em um ponto, não fiz para os outros :D A vida nos surpreende.

Muito obrigado.

**Comment by guaracy** [comment]
Renomear Conceptual.md para README.md não tem mistério e poderia encerrar por aqui. A dificuldade que poderia permanecer, apesar do nome dos arquivos indicar a sua funcionaldade, é: "Exatamente o que faz String.pas?"


A minha ideia seria, para cada fragmento, incluir uma linha no formato (e.g. Pascal):


[String.pas] : Por que Shortstring consome mais memória do que uma String comum? - [delphi]

- nome do programa com link para o fonte
- descrição (pergunta no Stackoverflow)
- link para a  página (https://pt.stackoverflow.com/q/205885/101)

A inclusão de novos fragmentos seriam feitas normalmente e só rodar o programa/script para gerar o arquivo novamente.

O resultado final do  README.md para Pascal ficaria (nomenclatura e formato TBD):

# Conceitos

- [Delphi é uma IDE ou linguagem de programação?](https://pt.stackoverflow.com/q/101695/101)
- [O Delphi possui coletor de lixo?](https://pt.stackoverflow.com/q/54919/101)
- [Que tipo de variável aloca menos memória, integer ou string?](https://pt.stackoverflow.com/q/357631/101)
- [Enviar mensagem para TV conectada na rede](https://pt.stackoverflow.com/q/87777/101)
- [O uso do Try no Delphi quando mal usado pode ser uma armadilha?](https://pt.stackoverflow.com/q/292615/101)
- [Comparação de variáveis de tipo diferente com conversão retorna resultado incorreto](https://pt.stackoverflow.com/q/307068/101)

---

# Exemplos

- [QueryBuilder.pas](QueryBuilder.pas) : Montando updates em tempo de execução - [java](https://pt.stackoverflow.com/q/130875/101)
- [Power.pas](Power.pas) : Como usar expoente em Pascal? - [matemática](https://pt.stackoverflow.com/q/230429/101)
- [String.pas](String.pas) : Por que Shortstring consome mais memória do que uma String comum? - [delphi](https://pt.stackoverflow.com/q/205885/101)
- [StringInArray.pas](StringInArray.pas) : Descobrir se item está em array - [delphi](https://pt.stackoverflow.com/q/37339/101)

**Comment by maniero** [comment]
Dá uma olhada. Eu fiz o que deu. Por requisitos não pude mexer tanto.

Eu ainda não sei se vale a pena *linkar* descrições para cada arquivo com código. Mas o tempo pode mudar isso e com mais sucesso eu resolver fazê-lo.

Se ainda tiver algo que possa ajudar estou ansioso por saber de você.

Muito obrigado por sua contribuição.
