### ISSUE TITLE
Qual o critério que você usa para trazer um código para cá?

### ISSUE THREAD

**Issue by lffg** [maniero/SOpt#6]
Vejo que em muitas respostas do SOpt você traz uma parte (ou a totalidade) do código para cá. Você tem algum critério para fazer isso? Estou pensando em começar a fazer algo assim...

**Comment by maniero** [comment]
Agora que eu vi aqui :D Eu não achei que alguém usaria um issue :D

Eu trago qualquer código que não seja tão mínimo que não sirva para nada. O maior motivo é ter um outro lugar para as pessoas verem um cookbook e ter garantias que eu terei esses códigos se um dia o SOpt sair do ar. Dá trabalho, mas eu sou perfeccionista :)

E claro que coloco também em pelo menos 2 sites de IDE online para a pessoa testar executando. Não deixo em um só porque é comum um deles estar fora do ar. Só não faço isso com JS porque eu acho que no próprio site é suficiente.

Estou quase terminando os antigos. Quero bolar algo mais legal pra usar o Github público esse ano. Aceito sugestões :)

**Comment by maniero** [comment]
Qual a vantagem? Como ele pode ser organizado como eu organizei?

**Comment by guibranco** [comment]
A vantagem seria ter eles de forma mais simples, já que são coisas isoladas e não correlacionadas. 
Organizado do jeito que está não ficaria, seriam links individuais que poderiam ser compartilhados em diversos lugares (não que no repositório não possa).

**Comment by maniero** [comment]
Não vi vantagem clara, nem mesmo ficar mais simples, e vi desvantagem, então por isso eu escolhi fazer assim. Mas se tiver algum outro motivo, manda aí. Obrigado pelo interesse e participação. Estou à disposição.
